### PR TITLE
Webpack 5 migration prep (update css loaders and webpack config)

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
This PR is the start of a long process to get us ready to upgrade to webpack 5.

It:
 * updates all the css loaders to the highest version that still support webpack 4. 
 * switches the use of autoprefixer to postcss-env (it includes autoprefixer among other plugins)
 * removes the custom function to output `mainfest.json` as it's not supported by webpack 5
 * adds the BundleAnalyzerPlugin to output the `manifest.json` file again
 * clean up the `webpack-config.js` file by removing options that won't be supported in webpack 5 or changing them to supported versions.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
Turns out there won't be a long process!

I have a stable version that use Webpack 5 locally and can push it here or add a separate PR after this is one merged.

Let me know what you think is best!

**Comment by madsnedergaard** [comment]
Lets do a separate PR to make testing easier :)

**Review by madsnedergaard — APPROVED** [review]
Tested and AFAIK it works just fine - so let's try it! 🙃

**Comment by VIKTORVAV99** [comment]
Hehe dev dependencies are the "safe" ones. 

It's when we need to update the production dependencies I start to worry. 😅

**Pull request merged**
