### PR TITLE
Update meta data to Electricity Maps

### PR DESCRIPTION
**Pull request by Kongkille**
Note: I also added ejs to package.json because I was not able to pass pre-commit

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
Lol I was just making a PR for this myself...

I'll check if all my changes match yours. 🙂

**Comment by VIKTORVAV99** [comment]
@Kongkille I had 2 other changes as well, the console.log message and the twitter badge on the readme. Do you mind if I commit those directly to this branch?

**Comment by Kongkille** [comment]
> @Kongkille I had 2 other changes as well, the console.log message and the twitter badge on the readme. Do you mind if I commit those directly to this branch?

Ah amazing! Please do

**Comment by VIKTORVAV99** [comment]
> > @Kongkille I had 2 other changes as well, the console.log message and the twitter badge on the readme. Do you mind if I commit those directly to this branch?
> 
> Ah amazing! Please do

Found a few more references to the old domain, is it safe to update app@electricitymap.org emails to app@electricitymaps.com?

**Comment by VIKTORVAV99** [comment]
> Yes it is now safe to use [app@electricitymaps.com](mailto:app@electricitymaps.com)

I updated the references everywhere but in the BUILD.yml file here as I wasn't sure if it would break something...
https://github.com/electricitymap/electricitymap-contrib/blob/13c9e2ed4a4b3a071c572a47eb1de46f0abf4e12/web/BUILD.yaml#L35-L38

**Review by tonypls — APPROVED** [review]

**Comment by Kongkille** [comment]
> > Yes it is now safe to use [app@electricitymaps.com](mailto:app@electricitymaps.com)
> 
> I updated the references everywhere but in the BUILD.yml file here as I wasn't sure if it would break something...
> 
> https://github.com/electricitymap/electricitymap-contrib/blob/13c9e2ed4a4b3a071c572a47eb1de46f0abf4e12/web/BUILD.yaml#L35-L38

Yeah there are still a few things that we have to keep for now. I'm intending to look at those in the future.

**Pull request merged**
