### PR TITLE
Fix capacity parser NL

### PR DESCRIPTION
**Pull request by pierresegonne**
The NL capacity parser was crashing for a while - making the whole parser crash.

### CODE REVIEW

**Review by gwpicard — APPROVED** [review]
🌬️ nice! Thanks for fixing 😄

**Comment by pierresegonne** [comment]
Hey @q-- :)

The NL data will always be estimated, we have a model on top of the ENTSO-E data, as it is missing a lot of solar and gas production.

**Comment by mhooi** [comment]
> Hey @q-- :)
> 
> The NL data will always be estimated, we have a model on top of the ENTSO-E data, as it is missing a lot of solar and gas production.

Do you have a link to the location where is explained how the NL data is estimated?

**Comment by pierresegonne** [comment]
Hey @mhooi, we are currently using a model of that class: https://github.com/electricitymap/electricitymap-contrib/wiki/Reconstruct-Breakdown

I recognise though that it would be nicer to propagate production for modes we know are reliable as is done for CH

**Comment by mhooi** [comment]
> Hey @mhooi, we are currently using a model of that class: https://github.com/electricitymap/electricitymap-contrib/wiki/Reconstruct-Breakdown
> 
> I recognise though that it would be nicer to propagate production for modes we know are reliable as is done for CH

Thanks for the quick reply. I did find the theoretical framework already. 

But where can I find the model and understand that for example the model estimates that the current solar production is 3.63 GW while in reality the actual number is more like 10 GW?

**Pull request merged**
