### PR TITLE
Allow missing entries in data

### LINKED ISSUE #4398: Allow missing entries in time window
## Description

Cause of #4387. 

The app-backend currently either returns nothing or all expected values. For example for 24 hours, if one hour is missing data completely we will not return any values.

This was implemented to ensure we do not become out of sync with history and state (#3949) and also to minimize the file sizes.

I.e if the length of the array is 24 and the other is 25 but the index is shared, the state and history will become out of sync.

## Solution

The main cause of complexity here is that we use an index to keep track of time. We use 'selectedZoneTimeIndex' which is an index that can both be used in history and state.

I think the optimal solution would be to deprecate 'selectedZoneTimeIndex' and instead simply have a 'selectedDatetime' and change the data structure to map from datetime to zoneData instead of using an index to map to zoneData.

I believe this is more intuitive to work with and guarantees that we do not become out of sync.

Alternative solution:

A potentially less demanding solution would just be to fill in missing values in the array. I.e. we always ensure that there is 24 entries for 24 hours and 5 values for 5 years.

### PR DESCRIPTION
**Pull request by Kongkille**
Fixes #4398 and #4387

I was touching the countryPanel, and decided to split it up to not add even more functionality to a crowded component. Arguably that could have been another PR but I think there's a lot of tech debt around in our components and it's OK that we clean up a bit while adding functionality.

Bonus: also enabled the hiring RSS which had been broken with the domain change

This requires some changes to the backend, but we can still merge this one and I'll make sure to release the app-backend and this one in the same update.

### CODE REVIEW

**Comment by Kongkille** [comment]
Cypress failling because I updated mockdata, i'll fix it

**Comment by Kongkille** [comment]
> I'm curious as to what will happen is there is just one or few co2intensity values for a period and how this will display in a graph.
> 
> Also there are still "hasData" variables in helpers/redux.js and dataReducer.js, these are meant to remain right?

Yes it won't look super good, however this is almost never the case. At least I haven't seen a case of this. 

And yes, so the idea was that 'hasData' defines whether there is any data for the zone and the isValid is per entry.

**Comment by tonypls** [comment]
lgtm 👍

**Comment by strassburger** [comment]
@Kongkille 
Thanks, now the 5year data is shown for El Hierro, at least last 4 years data are shown.
 2017 data still missing.
Checked first possible data  2012-03-01, Source:
https://demanda.ree.es/visiona/canarias/el_hierro5m/total/2012-03-01
Checked every single day, some days looked like data was generated just in the moment i asked for.

Looks like same for all canary Island data.
Also learned that El Hierro did not get really better in Co2 results, but spanish mainland is really getting better in CO2 last five years.

**Comment by Kongkille** [comment]
That's great. Yeah so we don't have 2017 yet, but now we're able to show the other years!

**Pull request merged**
