### PR TITLE
fix(GCCIA): fix consumption data fetch for AE, BH, OM, QA, and SA

### PR DESCRIPTION
**Pull request by shuuji3**
These countries using `parsers/GCCIA.py` had the same errors:

```py
'<' not supported between instances of 'dict' and 'int'
  File "/home/contrib/electricitymap/contrib/parsers/lib/quality.py", line 33, in validate_consumption
    if (obj.get("consumption") or 0) < 0:
```

ref. https://storage.googleapis.com/electricitymap-parser-logs/AE.html

This was because `fetch_consumption()` returned dictionary as a consumption (i.e. `{"unknown": 123}`). I guess it was confused with `fetch_production()`. This PR fixes the function to return int value as a consumption value.

Also, SA is currently showing  " - " instead of a value like "123 MW". I added a check if the value is currently available and made it raise `RuntimeError`. Is it OK to raise `RuntimeError` to handle a case like this?

ref. https://storage.googleapis.com/electricitymap-parser-logs/SA.html

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
I believe a ParserException would be a better fit than a runtime error.
Import it with:
```python 
from .lib.exceptions import ParserException 
```

Besides that I'll try and do a full review tomorrow.

**Comment by shuuji3** [comment]
Thank you. I replaced it with `ParserException`.

**Comment by shuuji3** [comment]
Thank you. I replaced it with ParserException.

**Review by VIKTORVAV99 — APPROVED** [review]
Changes in here works great.
And since the data source have not changed it should be perfectly safe to merge it.

**Comment by shuuji3** [comment]
@VIKTORVAV99 Thanks for reviewing!

By the way, I saw that several parsers use `RuntimeError`: https://github.com/electricitymap/electricitymap-contrib/search?q=RuntimeError. Do you think it's helpful to use `ParserException` in those parsers (for example, it makes it easy to understand issues)? If so, I'd like to improve those parsers using `ParserException`.

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99 Thanks for reviewing!
> 
> By the way, I saw that several parsers use `RuntimeError`: https://github.com/electricitymap/electricitymap-contrib/search?q=RuntimeError. Do you think it's helpful to use `ParserException` in those parsers (for example, it makes it easy to understand issues)? If so, I'd like to improve those parsers using `ParserException`.

ParserException is probably better since it provides more information. So if you want to update them go for it! 🎉

**Comment by shuuji3** [comment]
OK, I'll do it! 😀

**Pull request merged**
