### PR TITLE
Revert se split and exchanges config updates

### PR DESCRIPTION
**Pull request by pierresegonne**
## Issue

We're pushing back the release of the SE split, as it's blocking on our side. 

### Preview
Screenshot 2022-08-19 at 16 54 01

I can run the frontend locally but for some reason the mockserver crashes

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
The mockserver is running fine for me locally, anything specific you did that might have crashed it?

**Review by VIKTORVAV99 — COMMENTED** [review]
LGTM! But I'll let @FelixDQ approve it unless he finds something blocking.

And don't worry, like I already told you this is perfectly fine, it will be merged eventually when everything is ready and that is all that matters.

**Comment by pierresegonne** [comment]
Great! Thanks a lot for the constructive approach. Yeah let's update the exchanges and get everything integrated.

**Comment by VIKTORVAV99** [comment]
> Great! Thanks a lot for the constructive approach. Yeah let's update the exchanges and get everything integrated.

I can commit the exchange aggregate in here but I think it might be a better fit for #4457 as it changes all the exchanges to ENTSO-E anyway.

**Review by Kongkille — APPROVED** [review]

**Pull request merged**
