### PR TITLE
GE: retrieve historical exchange data via ENTSOE

### PR DESCRIPTION
**Pull request by q--**
The GSE data source has real-time data, so you're not dealing with larger intervals like ENTSO-E. However, there is no historical exchange data from this data source. This pull request will obtain that data from the ENTSOE parser when a target datetime is specified.

Related: #3408

----
Not really tested other than checking for syntax errors, please test this before merging.

### CODE REVIEW

**Comment by pierresegonne** [comment]
FYI I updated the branch, as an issue with circle-ci forced me to change the commands on the build steps. :)

**Review by madsnedergaard — APPROVED** [review]
Nice that it was so simple - and it just works :)

Screenshot 2022-04-21 at 09 22 25

**Comment by VIKTORVAV99** [comment]
@q-- perhaps you want to do the same for Croatia (HR)?
(HOPS.py parser)

Should be just as simple.

**Comment by q--** [comment]
@VIKTORVAV99 Not planning to work on it soon, feel free to create a PR yourself

**Comment by VIKTORVAV99** [comment]
@q-- okay, I'll see if I can put something together this weekend then.

**Pull request merged**
