### PR TITLE
Reduce expected range for Slovenia down to 800MW

### PR DESCRIPTION
**Pull request by DavidKarlas**
With TEŠ 6(coal power plant) going offline for 12 days according to https://iip.remitor.eu/#/message/view/8780
Slovenia production can drop below 1GW.
~690MW coming from Nuclear, ~7MW Biomass, ~45MW Gas and Hydro can go down to ~50MW(currently with rain and snow melting its around ~100MW).
I think it will never drop under 800MW, 900MW might also work, but not always...

### CODE REVIEW

**Comment by DavidKarlas** [comment]
Validation is failing again: https://storage.googleapis.com/electricitymap-parser-logs/SI.html

**Review by madsnedergaard — APPROVED** [review]
Thanks for updating this! 💪

**Comment by q--** [comment]
> `         'required': ['nuclear'],`

Does this need fixing as well? The country only has a single NPP which sometimes is unavailable due to refueling.

**Comment by DavidKarlas** [comment]
I found that surprising as well, I just assumed it means that even if 0 is reported is passing the validation...

**Pull request merged**
