### PR TITLE
fix(JP): fix date comparison error in  `price` parser

### LINKED ISSUE #4346: JP: fix "No recent data found for `price` parser" error
Hello, I noticed `price` parser errors on [this Wiki page](https://github.com/electricitymap/electricitymap-contrib/wiki/Parser-issues). This is due to comparison errors at `parsers/JP.py`:

```py
electricityMap.org recent parser errors for JP-TK
Last updated: Sat, 16 Jul 2022 06:01:59+0000

timestamp	severity	zone_key	message
2022-07-16T05:43:55	ERROR     	JP-TK     	Invalid comparison between dtype=datetime64[ns] and date

  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/contrib/parsers/lib/config.py", line 15, in wrapped_f
    result = f(*args, **kwargs)
  File "/home/contrib/parsers/JP.py", line 312, in fetch_price
    df = df[(df["Date"] >= start.date()) & (df["Date"] <= target_datetime.date())]
  File "/usr/local/lib/python3.8/site-packages/pandas/core/ops/common.py", line 69, in new_method
    return method(self, other)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/arraylike.py", line 52, in __ge__
    return self._cmp_method(other, operator.ge)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 5502, in _cmp_method
    res_values = ops.comparison_op(lvalues, rvalues, op)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 270, in comparison_op
    res_values = op(lvalues, values)      
```
https://storage.googleapis.com/electricitymap-parser-logs/JP-TK.html (same as other JP parsers)

This error affects all parsers for Japan except JP-ON (Okinawa). JP-ON raises another 404 not found error (https://storage.googleapis.com/electricitymap-parser-logs/JP-ON.html).

I will create a PR to fix this error.

### PR DESCRIPTION
**Pull request by shuuji3**
resolves #4346

This is because `df['Date']` column has `datetime64[ns]` dtype instead of `datetime.date` type. This change convert it to `datetime.date` by `.dt.date` attribute.

I also used Pandas' `pd.to_datetime()` method instead of `DataFrame.apply()` for code readability.

### CODE REVIEW

**Review by VIKTORVAV99 — APPROVED** [review]
Hi and Welcome!

This is a really nice fix!
I'll go ahead and merge this right away. 🎉

**Comment by shuuji3** [comment]
@VIKTORVAV99 Thanks for taking a look! I love this project. I live in Japan and can read resources written in Japanese so I'd like to contribute more especially in Japan area if any.

**Comment by VIKTORVAV99** [comment]
Hmm, the CircleCI checks don't appear to be running (and I can't merge without them...)

@Kongkille do you have any idea why?
I tried triggering them manually on CircleCI but I can't even seem to find this PR on the dashboard.

**Comment by VIKTORVAV99** [comment]
> @VIKTORVAV99 Thanks for taking a look!🙂 I love this project. I live in Japan and can read resources written in Japanese so I'd like to contribute more especially in Japan area if any.

Thanks for helping out, if you want something to do right away you could look over the translations, I know we recently added a few more strings to translate and I don't think we have a Japanese translation for those yet.

Otherwise I think it's the usual things like keeping the capacities updated  such that's needed for now.

Only do what you can (some can take a lot of time) and feel comfortable with though, any contribution however small is appreciated!

**Comment by shuuji3** [comment]
Thanks for your advice. I can update the Japanese translation.

**Pull request merged**
