### PR TITLE
Update favicon and PWA icons

### PR DESCRIPTION
**Pull request by steren**
This PR modernizes the icons:

* Add an SVG favicon (supported by all but Safari)
* Add support for dark theme in SVG favicon:
image

* Remove small apple-touch icons
* Remove optional MS icons (the favicon is used instead)
* Update `manifest.json` for better "installable" experience:

  - define background and theme color
  - Use svg icons
  - Add [maskabke icon](https://web.dev/maskable-icon/) (tested using https://maskable.app/)

### CODE REVIEW

**Review by madsnedergaard — APPROVED** [review]
Awesome, looks much better! 🥳

**Comment by madsnedergaard** [comment]
My Chrome now looks like this - dunno if I have some setting enabled somewhere that turns the browser to dark-mode despite system not being in dark-mode? 😄 

Screenshot 2022-01-04 at 15 03 55

**Comment by steren** [comment]
Strange, I believe I tested all on the local server.
I can investigate later this week. Feel free to revert the changes in the meantime.

**Comment by steren** [comment]
I have found https://github.com/electricitymap/electricitymap-contrib/pull/3643 but it doesn't explain what you observe.

Has the change rolled out to prod by the way ? I am still seeing the old one.

**Comment by steren** [comment]
I confirm the icon renders well on Chrome windows dark and light mode. 
What browser / OS are you using ?

**Comment by steren** [comment]
When you tested, did you recently switched from light theme? 
favicons have some caching and it appears that Chrome doesn't refresh the cache on light / dark theme change.

So if you open electricityMap in light mode, then switch to dark mode, Chrome will not update the favicon instantly. I reproduced this on mac and Windows.

I believe that's an acceptable experience.

**Comment by madsnedergaard** [comment]
Thanks for investigating! It turns out I had a dark theme installed in Chrome that I missed 🤦
Sorry for taking your time and thanks again for making the change!

**Pull request merged**
