### PR TITLE
Updates /web and /mobileapp dependencies at once

### PR DESCRIPTION
**Pull request by madsnedergaard**
Dont want to wait for CI to run on 20 different PRs and manually update-master and merge every single one of them... So doing a few bulk updates instead!

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
@madsnedergaard for the record dependabot will automatically close PR that aren't relevant anymore so you don't have to close them all one by one. Merging this would have closed them all. :)

**Review by Kongkille — APPROVED** [review]

**Comment by madsnedergaard** [comment]
> @madsnedergaard for the record dependabot will automatically close PR that aren't relevant anymore so you don't have to close them all one by one. Merging this would have closed them all. :)

Ah cool, thanks :D

**Comment by VIKTORVAV99** [comment]
@madsnedergaard @Kongkille I just noticed something, this only updates the lockfiles and not the package.json as well, was this intended?

**Comment by madsnedergaard** [comment]
> @madsnedergaard @Kongkille I just noticed something, this only updates the lockfiles and not the package.json as well, was this intended?

Yup, there's no easy way to update package.json dependencies with yarn :/ 
But as far as I can tell it's also not that important - as long as we're using semver range specifiers (tilde and caret), then yarn will only look at the lockfile.

**Comment by VIKTORVAV99** [comment]
You are right it don't seem very important, I expected yarn to overwrite the lockfile when running `yarn install` (like npm) but it didn't so it looks like this will work just fine.

**Pull request merged**
