### PR TITLE
Webpack 5 follow up

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
Follow up PR for the Webpack 5 update.

#### In this PR:
- Update all loaders and webpack plugins to the latest version.
- Switches `sass` to `sass-embedded`.
- Bumps `@babel` packages.

~~Requires #4132 to be merged first for the nodejs version bump.~~ #4132 have now been merged.

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
@Kongkille your Cypress tests appear to be acting up again, this time it's the API tests...

**Comment by Kongkille** [comment]
> @Kongkille your Cypress tests appear to be acting up again, this time it's the API tests...

Ah yeah thats annoying. I'll look into this today

**Comment by VIKTORVAV99** [comment]
> > @Kongkille your Cypress tests appear to be acting up again, this time it's the API tests...
> 
> Ah yeah thats annoying. I'll look into this today

I think it boils down to the fact that forks does not have access to secrets so it can't find the snowpack token that causes the API request to fail.

**Comment by Kongkille** [comment]
> > > @Kongkille your Cypress tests appear to be acting up again, this time it's the API tests...
> > 
> > 
> > Ah yeah thats annoying. I'll look into this today
> 
> I think it boils down to the fact that forks does not have access to secrets so it can't find the snowpack token that causes the API request to fail.

Yeah I think you're right. I'll change to using the mockserver for now :)

**Review by madsnedergaard — APPROVED** [review]
It took a while, but I've finally had time to test this! :)

**Pull request merged**
