### PR TITLE
`HU->SI` (new exchange)

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
It looks like Hungary and Slovenia has a [interconnector now (or will very soon)](https://www.eles.si/en/news/ArticleID/18607/Update-of-the-construction-of-cross-border-transmission-line-between-Slovenia-and-Hungary).
The exchange data is not yet being reported to ENTSO-E but it has it's own data fields now.

I wanted to get this added before it becomes operational so we don't miss any exchanges between the countries when it does go live. (Hopefully they will start reporting the exchange volumes immediately too).

I also added exchange forecasts for some of Hungary's exchanges that have non-NaN values in ENTSO-E.

PS: I manually edited the state file so the new exchange would show up on local development, if there is any issues with that just let me know and I'll just remove those changes as they aren't really needed. 

EDIT:
Link to [ENTSO-E data](https://transparency.entsoe.eu/transmission-domain/physicalFlow/show?name=&defaultValue=false&viewType=TABLE&areaType=BORDER_BZN&atch=false&dateTime.dateTime=30.06.2022+00:00|UTC|DAY&border.values=CTY|10YHU-MAVIR----U!BZN_BZN|10YHU-MAVIR----U_BZN_BZN|10YSI-ELES-----O&dateTime.timezone=UTC&dateTime.timezone_input=UTC).

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
Looks like the exchange will go live tomorrow according to ENTSO-E:
> Dear Transparency Platform Users,
>
>MAVIR and ELES would like to inform, that the new 400 kV transmission line connection will be put into operation on the Hungarian-Slovenian border on June 30, 2022. Relevant publications related to the new transmission line connection can be viewed on the Transparency Platform.
> 
>Best regards,
> 
>MAVIR, ELES and Transparency Platform Team

**Comment by VIKTORVAV99** [comment]
And data is flowing! (at 15 min resolution less) 🎉

**Comment by VIKTORVAV99** [comment]
@madsnedergaard it would be great if we could merge this quickly as the exchange is active now with significant flows.

image

200 MW should be around 10% of Slovenia's current electricity consumption.

**Review by madsnedergaard — APPROVED** [review]
Nice work here 👏

**Comment by DavidKarlas** [comment]
@madsnedergaard will this automatically appear in UI in few days or does something else needs to change?

**Comment by DavidKarlas** [comment]
> @madsnedergaard it would be great if we could merge this quickly as the exchange is active now with significant flows.
> 
> 
> 
> image
> 
> 
> 
> 200 MW should be around 10% of Slovenia's current electricity consumption. 

Thank you for the work from Slovenia 😃 
About 200MW... It is very often that we send 1GW to Italy while max Slovenia consumption is 2GW... We usually import that from Austria, and now I assume from Hungary..

**Comment by VIKTORVAV99** [comment]
> @madsnedergaard will this automatically appear in UI in few days or does something else needs to change?

Mads is on paternity leave for the next months but yes this will show up on the map as soon as a new release has been published.

Sadly as I'm not on the electricityMap team I can't push a release myselfb so all we can do is wait. (the data should be back filled tho)

**Comment by VIKTORVAV99** [comment]
> > @madsnedergaard it would be great if we could merge this quickly as the exchange is active now with significant flows.
> > image
> > 200 MW should be around 10% of Slovenia's current electricity consumption.
> 
> Thank you for the work from Slovenia 😃 About 200MW... It is very often that we send 1GW to Italy while max Slovenia consumption is 2GW... We usually import that from Austria, and now I assume from Hungary..

Thank you for the kinds words!
It does indeed look like a significant portion of the net imports now come from Hungary, the highest I have seen so far is 580 MW. Hopefully a new release will be published soon so we can see it on the app/map as well!

**Pull request merged**
