### PR TITLE
Update mobile assets and copy

### PR DESCRIPTION
**Pull request by Kongkille**
Following up on rebranding, our assets on iOS and Android are outdated.

Additional checklist for updating to a new version

- [x] Update launch screen on IOS 
- [x] Rename app
- [x] Update app store splash images
- [x] Update play store images

### CODE REVIEW

**Comment by Kongkille** [comment]
Testflight issue:

Modal overlay seems to not cover all the way down

image

Iphone SE

**Comment by Kongkille** [comment]
Currently blocked until I fix the deploy script

https://github.com/electricitymap/electricitymap-contrib/commit/26eb34830b6f3dfaa4d974bef794f64437063027

**Comment by Kongkille** [comment]
Ran deploy locally and it seems to work

**Comment by Kongkille** [comment]
Mobile apps pending rollout, just waiting for IOS approval before merging this PR
 
cc @corradio

**Comment by corradio** [comment]
> Mobile apps pending rollout, just waiting for IOS approval before merging this PR
> 
> cc @corradio

yay!

**Pull request merged**
