### PR TITLE
Split Sweden to bidding zones

### PR DESCRIPTION
**Pull request by morganchristiansson**
Attempt to use `ENTSOE.query_production` instead of `SE.fetch_production`.

Refs #1397

image

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
This is currently blocked by issue #1395. I'd love to see more granular data for Sweden though.

**Comment by jarek** [comment]
Unfortunately, no exchanges between the zones makes this not that accurate :/

**Comment by gwpicard** [comment]
You should decide here whether to keep this once or #3936 -- and either way, this PR is blocked until we can support multiple levels of spatial granularity!

**Comment by VIKTORVAV99** [comment]
@gwpicard I might be a bit biased due to the fact I created the other PR but I did it partly because this PR is missing a lot of steps (could be rectified), use the old geometry system and currently have merge conflicts.
So my vote is we keep #3936 and close this PR.

**Comment by gwpicard** [comment]
> @gwpicard I might be a bit biased due to the fact I created the other PR but I did it partly because this PR is missing a lot of steps (could be rectified), use the old geometry system and currently have merge conflicts. So my vote is we keep #3936 and close this PR.

I'll let you decide among yourselves if @morganchristiansson agrees with it!

**Comment by VIKTORVAV99** [comment]
@gwpicard I'm going to close this PR as we have gotten no response from @morganchristiansson and #3936  is ready to merge now (pending reviews).

**Pull request closed without merging**
