### PR TITLE
Archive broken and unused parsers

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
This PR moves to archive parsers that are either broken for a long time or no longer used as discussed in #3473.

In this PR:
- Moves archived parsers to `/archived` folder directly under `/parsers`.
- Archived Parsers
  - `AM.py` - Reason: Data no longer available.
  - `GB_NIR.py` - Reason: Data no longer available.
  - `IN_UP.py` - Reason: Data no longer available.
  - `JP_ISEP.py` - Reason: Unused.
  - `SE.py` - Reason: Unused.
  - `US_BPA.py` - Reason: Unused.
  - `XK.py` - Reason: Unused.
- Updated labeler config to add "archived parser" instead of parser label for archived parsers.
- Removed references to archived parsers from `zones.json` and `exchanges.json`.
- Updated parser `README.md`

Note: I archived the parsers that has been unavailable for a long time plus SE.py since it is unused now. Please let me know if I should add more parsers to the archive or if I should remove one of the ones I have already added.

### CODE REVIEW

**Comment by madsnedergaard** [comment]
This is great(!), I can't think of anything missing from just rolling with this :)
But cc @pierresegonne and @Kongkille in case you guys have some thoughts or can think of something I'm missing on the backend-side?

**Comment by pierresegonne** [comment]
Not on my side, Just FYI @VIKTORVAV99 the test that checks the parser interface gives out what parsers are unused

**Comment by VIKTORVAV99** [comment]
> Not on my side, Just FYI @VIKTORVAV99 the test that checks the parser interface gives out what parsers are unused

Great! I'll go ahead and move those too.

**Review by madsnedergaard — APPROVED** [review]
Nice, let's merge this! 😎

**Pull request merged**
