### PR TITLE
Fix icons in mobile app.

### PR DESCRIPTION
**Pull request by VIKTORVAV99**
This should fix the icons in the mobile app if the problem is what I think it is while keeping the svg sprite for the web.

Now I am not really sure how to test this in a app setting (on a phone/emulator) but I did make sure all styles are the same when possible where it was applicable.

Closes: #4181

### CODE REVIEW

**Comment by madsnedergaard** [comment]
Awesome, I'll test it today! :)

**Comment by madsnedergaard** [comment]
There's unfortunately still an issue, I'll try to dive deeper into why:

Screenshot 2022-05-25 at 16 42 08


You can also run the iOS simulator like this by the way:
```bash
cd mobileapp
docker-compose build web  && ./build.sh
cordova run ios
```

**Comment by madsnedergaard** [comment]
Oh, turns out the fix was extremely simple 😅

**Comment by VIKTORVAV99** [comment]
> There's unfortunately still an issue, I'll try to dive deeper into why:
> 
> Screenshot 2022-05-25 at 16 42 08
> 
> You can also run the iOS simulator like this by the way:
> 
> ```shell
> cd mobileapp
> docker-compose build web  && ./build.sh
> cordova run ios
> ```

Thanks for the build steps!

At least there are question marks now, that's some improvement at least? 😅

**Pull request closed without merging**
